"""PHONE must be unique

Revision ID: 319b8a9e6354
Revises: 957a2fd6de33
Create Date: 2024-12-08 11:49:39.106204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319b8a9e6354'
down_revision: Union[str, None] = '957a2fd6de33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'clients', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    # ### end Alembic commands ###
