"""add nullable fields, revert back Street + new relation CLIENT - STREET

Revision ID: 957a2fd6de33
Revises: 38172a96e394
Create Date: 2024-12-08 11:23:14.224427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957a2fd6de33'
down_revision: Union[str, None] = '38172a96e394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streets_id'), 'streets', ['id'], unique=False)
    op.add_column('clients', sa.Column('street_id', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('apartment', sa.String(), nullable=True))
    op.create_foreign_key(None, 'clients', 'streets', ['street_id'], ['id'])
    op.drop_column('clients', 'address')
    op.alter_column('orders', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('clients', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'apartment')
    op.drop_column('clients', 'street_id')
    op.drop_index(op.f('ix_streets_id'), table_name='streets')
    op.drop_table('streets')
    # ### end Alembic commands ###
