"""Relations

Revision ID: d4ed0124ae67
Revises: b2c20dd5c380
Create Date: 2024-12-08 00:47:42.285961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ed0124ae67'
down_revision: Union[str, None] = 'b2c20dd5c380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza_doughs',
    sa.Column('pizza_id', sa.Integer(), nullable=False),
    sa.Column('dough_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dough_id'], ['doughs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pizza_id', 'dough_id')
    )
    op.create_table('pizza_ingredients',
    sa.Column('pizza_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pizza_id', 'ingredient_id')
    )
    op.create_table('order_pizzas',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('pizza_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'pizza_id')
    )
    op.add_column('addresses', sa.Column('street_id', sa.Integer(), nullable=False))
    op.add_column('addresses', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'addresses', 'streets', ['street_id'], ['id'])
    op.create_foreign_key(None, 'addresses', 'clients', ['client_id'], ['id'])
    op.add_column('clients', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'addresses', ['address_id'], ['id'])
    op.add_column('orders', sa.Column('client_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'client_id')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'address_id')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'client_id')
    op.drop_column('addresses', 'street_id')
    op.drop_table('order_pizzas')
    op.drop_table('pizza_ingredients')
    op.drop_table('pizza_doughs')
    # ### end Alembic commands ###
