version: "3.9"
services:
  backend:
      container_name: pizza-backend
      build:
        context: .
      ports:
        - "8005:8005"
      environment:
        - DATABASE_URL=postgresql://user:pizza123@db:5432/pizzeria
      depends_on:
        - db
      volumes:
        - .:/app

  db:
    container_name: pizza-db
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pizza123
      POSTGRES_DB: pizzeria
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
