"""additional-ingredients UNIQUE

Revision ID: 18d056eb3d80
Revises: 754f232ec44f
Create Date: 2025-01-04 13:12:27.473820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d056eb3d80'
down_revision: Union[str, None] = '754f232ec44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_order_pizza_ingredient_quantity_uc', 'additional_ingredients', type_='unique')
    op.create_unique_constraint('_order_pizza_ingredient_uc', 'additional_ingredients', ['order_pizza_id', 'ingredient_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_order_pizza_ingredient_uc', 'additional_ingredients', type_='unique')
    op.create_unique_constraint('_order_pizza_ingredient_quantity_uc', 'additional_ingredients', ['order_pizza_id', 'ingredient_id', 'quantity'])
    # ### end Alembic commands ###
