"""delete next relation -> PIZZA -> DOUGH

Revision ID: 38172a96e394
Revises: 66aa6d00aa30
Create Date: 2024-12-08 09:56:05.537456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38172a96e394'
down_revision: Union[str, None] = '66aa6d00aa30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizza_doughs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza_doughs',
    sa.Column('pizza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dough_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dough_id'], ['doughs.id'], name='pizza_doughs_dough_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], name='pizza_doughs_pizza_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pizza_id', 'dough_id', name='pizza_doughs_pkey')
    )
    # ### end Alembic commands ###
