"""is_partial: bool PIZZA ORDERS

Revision ID: 5ad328379a10
Revises: 6e030a96b5a5
Create Date: 2024-12-25 04:09:23.174862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad328379a10'
down_revision: Union[str, None] = '6e030a96b5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_pizzas', sa.Column('is_partial', sa.Boolean(), default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_pizzas', 'is_partial: Boolean')
    # ### end Alembic commands ###
