"""expand table order_pizzas

Revision ID: 66aa6d00aa30
Revises: 87436c2503b0
Create Date: 2024-12-08 09:49:52.122777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66aa6d00aa30'
down_revision: Union[str, None] = '87436c2503b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_pizzas', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_pizzas', 'quantity')
    # ### end Alembic commands ###
