"""additional-ingredients

Revision ID: 688fd07a24b7
Revises: b316bd4cf563
Create Date: 2025-01-04 10:25:30.196668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688fd07a24b7'
down_revision: Union[str, None] = 'b316bd4cf563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_ingredients',
    sa.Column('order_pizza_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_pizza_id'], ['order_pizzas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_pizza_id', 'ingredient_id')
    )
    op.drop_table('pizza_doughs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza_doughs',
    sa.Column('pizza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dough_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dough_id'], ['doughs.id'], name='pizza_doughs_dough_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], name='pizza_doughs_pizza_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pizza_id', 'dough_id', name='pizza_doughs_pkey')
    )
    op.drop_table('additional_ingredients')
    # ### end Alembic commands ###
