"""additional-ingredients with quantity DROP

Revision ID: 68b6c2b41984
Revises: 96841afddbc1
Create Date: 2025-01-04 11:30:13.430012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b6c2b41984'
down_revision: Union[str, None] = '96841afddbc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('additional_ingredients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_ingredients',
    sa.Column('order_pizza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name='additional_ingredients_ingredient_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_pizza_id'], ['order_pizzas.id'], name='additional_ingredients_order_pizza_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_pizza_id', 'ingredient_id', name='additional_ingredients_pkey')
    )
    # ### end Alembic commands ###
