"""additional-ingredients not quanti

Revision ID: 844fd6b3e13c
Revises: 688fd07a24b7
Create Date: 2025-01-04 10:38:08.787555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844fd6b3e13c'
down_revision: Union[str, None] = '688fd07a24b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('additional_ingredients', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additional_ingredients', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
