"""order pizzas drop

Revision ID: 85f871d86819
Revises: 5ad328379a10
Create Date: 2025-01-04 08:51:00.160430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f871d86819'
down_revision: Union[str, None] = '5ad328379a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_pizzas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_pizzas',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pizza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dough_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_partial', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dough_id'], ['doughs.id'], name='order_pizzas_dough_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_pizzas_order_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], name='order_pizzas_pizza_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'pizza_id', name='order_pizzas_pkey')
    )
    # ### end Alembic commands ###
