"""delete ENUM field

Revision ID: 87436c2503b0
Revises: cc34a22ddf2e
Create Date: 2024-12-08 09:44:37.186644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87436c2503b0'
down_revision: Union[str, None] = 'cc34a22ddf2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_pizzas', sa.Column('dough_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order_pizzas', 'doughs', ['dough_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_pizzas', type_='foreignkey')
    op.drop_column('order_pizzas', 'dough_id')
    # ### end Alembic commands ###
