"""additional-ingredients with quantity

Revision ID: 96841afddbc1
Revises: 844fd6b3e13c
Create Date: 2025-01-04 11:11:07.330041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96841afddbc1'
down_revision: Union[str, None] = '844fd6b3e13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additional_ingredients', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('additional_ingredients', 'quantity')
    # ### end Alembic commands ###
