"""additional-ingredients UNIQUE

Revision ID: b11c7a3b7f13
Revises: 4c8be586d395
Create Date: 2025-01-04 13:06:53.768854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11c7a3b7f13'
down_revision: Union[str, None] = '4c8be586d395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_order_pizza_ingredient_quantity_uc', 'additional_ingredients', ['order_pizza_id', 'ingredient_id', 'quantity'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_order_pizza_ingredient_quantity_uc', 'additional_ingredients', type_='unique')
    # ### end Alembic commands ###
