"""delete ENUM field

Revision ID: cc34a22ddf2e
Revises: 25f7b3df1b12
Create Date: 2024-12-08 09:28:55.161072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc34a22ddf2e'
down_revision: Union[str, None] = '25f7b3df1b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'category',
               existing_type=postgresql.ENUM('VEGETABLE', 'MEAT', 'DAIRY', name='ingredientcategory'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'category',
               existing_type=sa.String(),
               type_=postgresql.ENUM('VEGETABLE', 'MEAT', 'DAIRY', name='ingredientcategory'),
               existing_nullable=False)
    # ### end Alembic commands ###
