"""Transcript history logs

Revision ID: cd7dc0a03ddd
Revises: 45c01764cc3f
Create Date: 2025-01-04 19:08:05.170098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7dc0a03ddd'
down_revision: Union[str, None] = '45c01764cc3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_logs', sa.Column('parsed', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription_logs', 'parsed')
    # ### end Alembic commands ###
