"""Transcript history log

Revision ID: d3cb75a21bf4
Revises: 2d7c8c6e1797
Create Date: 2025-01-04 17:00:18.877262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cb75a21bf4'
down_revision: Union[str, None] = '2d7c8c6e1797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription_logs',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('updated_slots', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders._id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_transcription_logs_id'), 'transcription_logs', ['_id'], unique=False)
    op.drop_index('ix_transcripts_id', table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_constraint('order_transcripts_transcript_id_fkey', 'order_transcripts', type_='foreignkey')
    op.create_foreign_key(None, 'order_transcripts', 'transcription_logs', ['transcript_id'], ['_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_transcripts', type_='foreignkey')
    op.create_foreign_key('order_transcripts_transcript_id_fkey', 'order_transcripts', 'transcripts', ['transcript_id'], ['_id'], ondelete='CASCADE')
    op.create_table('transcripts',
    sa.Column('_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_slots', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders._id'], name='transcripts_order_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id', name='transcripts_pkey')
    )
    op.create_index('ix_transcripts_id', 'transcripts', ['_id'], unique=False)
    op.drop_index(op.f('ix_transcription_logs_id'), table_name='transcription_logs')
    op.drop_table('transcription_logs')
    # ### end Alembic commands ###
